obj-m += fifo_driver.o

all:
	# make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
	make -C /home/sgd/1C_Linux/1C_Spring_2025_Linux/kernel/vroot/lib/modules/6.14.6/build M=$(PWD) modules
clean:
	# make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
	make -C /home/sgd/1C_Linux/1C_Spring_2025_Linux/kernel/vroot/lib/modules/6.14.6/build M=$(PWD) clean

